FROM ubuntu:16.04

# Prevent dpkg from asking questions
ARG DEBIAN_FRONTEND=noninteractive

# Install ramroot
COPY /initramfs-tools /etc/initramfs-tools

# Install dependencies
RUN apt-get update && \
    apt-get -y dist-upgrade && \
    apt-get -y install initramfs-tools pixz && \
    apt-get clean all

# Install the kernel (will auto-generate the ramroot-enabled initrd)
RUN apt-get -y install linux-image-virtual
